// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_favs from "./routes/(platform)/favs.tsx";
import * as $_id_ from "./routes/[id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $chars from "./routes/chars.tsx";
import * as $index from "./routes/index.tsx";
import * as $CharFavs from "./islands/CharFavs.tsx";
import * as $CharsDetallado from "./islands/CharsDetallado.tsx";
import * as $ListaChars from "./islands/ListaChars.tsx";
import * as $LogIn from "./islands/LogIn.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/favs.tsx": $_platform_favs,
    "./routes/[id].tsx": $_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/chars.tsx": $chars,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CharFavs.tsx": $CharFavs,
    "./islands/CharsDetallado.tsx": $CharsDetallado,
    "./islands/ListaChars.tsx": $ListaChars,
    "./islands/LogIn.tsx": $LogIn,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
